In [18]:
import pandas as pd
from pandas.core.interchange import column

adsl = pd.read_csv("../csv_file/ADSL_PDS2019.csv").set_index("SUBJID")
adsl

,TRT,ATRT,SXANY,DTHDYX,DTHX,PFSDYCR,PFSCR,DIAGMONS,AGE,SEX,B_WEIGHT,RACE,B_ECOG,HISSUBTY,DIAGTYPE
SUBJID,,,,,,,,,,,,,,,
1,panit. plus best supportive care,panit. plus best supportive care,Y,218,1,84,1,55.0,68,Male,48.0,White or Caucasian,Symptoms but ambulatory,No sub-type,Colon
2,Best supportive care,Best supportive care,Y,231,1,57,1,25.0,48,Male,88.0,White or Caucasian,Symptoms but ambulatory,Mucinous,Colon
4,Best supportive care,Best supportive care,Y,581,1,581,1,19.0,70,Female,57.0,White or Caucasian,Fully active,No sub-type,Colon
5,Best supportive care,Best supportive care,Y,15,1,15,1,7.0,68,Female,64.4,White or Caucasian,In bed less than 50% of the time,No sub-type,Colon
6,panit. plus best supportive care,panit. plus best supportive care,Y,286,1,112,1,30.0,56,Male,83.5,White or Caucasian,Fully active,No sub-type,Rectal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
458,Best supportive care,Best supportive care,Y,501,1,54,1,36.0,71,Female,63.0,White or Caucasian,Symptoms but ambulatory,No sub-type,Rectal
459,Best supportive care,Best supportive care,Y,485,0,55,1,NaN,32,Female,62.5,White or Caucasian,Fully active,No sub-type,Rectal
460,Best supportive care,Best supportive care,Y,64,1,46,1,39.0,53,Female,75.0,White or Caucasian,Fully active,No sub-type,Colon
461,panit. plus best supportive care,panit. plus best supportive care,N,175,1,53,1,9.0,76,Male,72.0,White or Caucasian,Fully active,No sub-type,Rectal
462,panit. plus best supportive care,panit. plus best supportive care,Y,504,1,61,1,45.0,66,Female,79.0,White or Caucasian,Fully active,No sub-type,Rectal

AttributeError: 'DataFrame' object has no attribute 'count_values'

In [24]:
adsl['TRT'].value_counts()

TRT
Best supportive care                186
panit. plus best supportive care    184
Name: count, dtype: int64

In [25]:
# 배정받은 치료법 이랑 실제 받은 치료법이 다른 사람 (SUBJID = 283)
adsl[adsl["TRT"] != adsl["ATRT"]]

,TRT,ATRT,SXANY,DTHDYX,DTHX,PFSDYCR,PFSCR,DIAGMONS,AGE,SEX,B_WEIGHT,RACE,B_ECOG,HISSUBTY,DIAGTYPE
SUBJID,,,,,,,,,,,,,,,
283,panit. plus best supportive care,Best supportive care,Y,1,1,1,1,35.0,67,Male,55.5,White or Caucasian,In bed less than 50% of the time,No sub-type,Colon

In [30]:
# 사망한 사람 (SUBJID)
adsl[adsl["DTHX"]==0].index

Index([ 34,  37,  68,  82, 123, 126, 140, 145, 149, 181, 221, 229, 233, 258,
       261, 271, 285, 292, 300, 304, 305, 336, 343, 357, 360, 371, 372, 373,
       376, 397, 409, 437, 445, 447, 459],
      dtype='int64', name='SUBJID')

In [16]:
import pandas as pd
adls = pd.read_csv("ADLS.csv")
adrsp = pd.read_csv("ADRSP.csv")
adls

,SUBJID,VISITDY,VISIT,LSCAT,LSNEW,LSSLD,LSLD,LSSITE,LSNEWANY,LSREADER,LSTYPE,Unnamed: 11,Unnamed: 12
0,1,85.0,Week 12,Target lesion,N,210.0,32.0,Liver,N,Radiologist 1,Central,ONCOLOGIST,156.0
1,1,85.0,Week 12,Target lesion,N,300.0,51.0,Liver,Y,Radiologist 2,Central,NaN,NaN
2,1,85.0,Week 12,Target lesion,N,210.0,53.0,Liver,N,Radiologist 1,Central,RADIALOGIST1,281.0
3,1,85.0,Week 12,Target lesion,N,300.0,37.0,Liver,Y,Radiologist 2,Central,NaN,NaN
4,1,85.0,Week 12,Target lesion,N,210.0,32.0,Liver,N,Radiologist 1,Central,RADIALOGIST 2,281.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9930,461,-1.0,Screening,Non-target lesion,N,245.0,NaN,Pulmonary,N,Radiologist 2,Central,NaN,NaN
9931,461,-1.0,Screening,Non-target lesion,N,219.0,NaN,Lymph Nodes,N,Radiologist 1,Central,NaN,NaN
9932,461,-1.0,Screening,Non-target lesion,N,245.0,NaN,Lymph Nodes,N,Radiologist 2,Central,NaN,NaN
9933,461,-1.0,Screening,Non-target lesion,N,219.0,NaN,Gastrointestinal,N,Radiologist 1,Central,NaN,NaN
9934,461,-1.0,Screening,Non-target lesion,N,245.0,NaN,Lymph Nodes,N,Radiologist 2,Central,NaN,NaN

In [8]:
adrsp

,SUBJID,RSRESP,VISITDY,VISIT,RSCONFYN,RSTRESP,RSNTRESP,RSREADER,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,1,Unknown,NaN,Screening,NaN,Unknown,Unknown,Radiologist 1,NaN,NaN,NaN
1,1,Unknown,NaN,Screening,NaN,Unknown,Unknown,Radiologist 2,NaN,ONCOLOGST,370.0
2,1,Unknown,NaN,Screening,NaN,Unknown,Unknown,Oncologist,NaN,NaN,NaN
3,1,Unable to evaluate,50.0,Week 8,NaN,Stable disease,Stable disease,Radiologist 1,NaN,RADIOLOGIST1,283.0
4,1,Unable to evaluate,50.0,Week 8,NaN,Stable disease,Stable disease,Radiologist 2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2297,461,Progressive disease,54.0,Week 8,NaN,Progressive disease,Progressive disease,Radiologist 1,NaN,NaN,NaN
2298,461,Progressive disease,54.0,Week 8,NaN,Progressive disease,Progressive disease,Radiologist 2,NaN,NaN,NaN
2299,461,Progressive disease,54.0,Week 8,NaN,Progressive disease,Progressive disease,Oncologist,NaN,NaN,NaN
2300,462,Unknown,NaN,Screening,NaN,Unknown,Unknown,Oncologist,NaN,NaN,NaN
2301,462,Progressive disease,62.0,Week 8,NaN,Not applicable,Progressive disease,Oncologist,NaN,NaN,NaN

In [17]:
adls = adls.drop(columns=["Unnamed: 11", "Unnamed: 12","LSTYPE"])
adrsp = adrsp.drop(columns=["Unnamed: 8","Unnamed: 9","Unnamed: 10"])

In [18]:
adls

,SUBJID,VISITDY,VISIT,LSCAT,LSNEW,LSSLD,LSLD,LSSITE,LSNEWANY,LSREADER
0,1,85.0,Week 12,Target lesion,N,210.0,32.0,Liver,N,Radiologist 1
1,1,85.0,Week 12,Target lesion,N,300.0,51.0,Liver,Y,Radiologist 2
2,1,85.0,Week 12,Target lesion,N,210.0,53.0,Liver,N,Radiologist 1
3,1,85.0,Week 12,Target lesion,N,300.0,37.0,Liver,Y,Radiologist 2
4,1,85.0,Week 12,Target lesion,N,210.0,32.0,Liver,N,Radiologist 1
...,...,...,...,...,...,...,...,...,...,...
9930,461,-1.0,Screening,Non-target lesion,N,245.0,NaN,Pulmonary,N,Radiologist 2
9931,461,-1.0,Screening,Non-target lesion,N,219.0,NaN,Lymph Nodes,N,Radiologist 1
9932,461,-1.0,Screening,Non-target lesion,N,245.0,NaN,Lymph Nodes,N,Radiologist 2
9933,461,-1.0,Screening,Non-target lesion,N,219.0,NaN,Gastrointestinal,N,Radiologist 1
9934,461,-1.0,Screening,Non-target lesion,N,245.0,NaN,Lymph Nodes,N,Radiologist 2

In [19]:
adrsp

,SUBJID,RSRESP,VISITDY,VISIT,RSCONFYN,RSTRESP,RSNTRESP,RSREADER
0,1,Unknown,NaN,Screening,NaN,Unknown,Unknown,Radiologist 1
1,1,Unknown,NaN,Screening,NaN,Unknown,Unknown,Radiologist 2
2,1,Unknown,NaN,Screening,NaN,Unknown,Unknown,Oncologist
3,1,Unable to evaluate,50.0,Week 8,NaN,Stable disease,Stable disease,Radiologist 1
4,1,Unable to evaluate,50.0,Week 8,NaN,Stable disease,Stable disease,Radiologist 2
...,...,...,...,...,...,...,...,...
2297,461,Progressive disease,54.0,Week 8,NaN,Progressive disease,Progressive disease,Radiologist 1
2298,461,Progressive disease,54.0,Week 8,NaN,Progressive disease,Progressive disease,Radiologist 2
2299,461,Progressive disease,54.0,Week 8,NaN,Progressive disease,Progressive disease,Oncologist
2300,462,Unknown,NaN,Screening,NaN,Unknown,Unknown,Oncologist
2301,462,Progressive disease,62.0,Week 8,NaN,Not applicable,Progressive disease,Oncologist

In [21]:
bio = pd.read_csv('../csv_file/biomark_preprocss.csv')
bio

,SUBJID,BMMTNM1,BMMTNM2,BMMTNM3,BMMTNM4,BMMTNM5,BMMTNM6,BMMTNM7,b1,b2,b3,b4,b5,b6,b7,n_mut,n_wild,n_fail,status
0,1,KRAS exon 2 (c12/13),KRAS exon 3 (c61),KRAS exon 4 (c117/146),NRAS exon 2 (c12/13),NRAS exon 3 (c61),NRAS exon 4 (c117/146),BRAF exon 15 (c600),Failure,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,Unknown
1,2,KRAS exon 2 (c12/13),KRAS exon 3 (c61),KRAS exon 4 (c117/146),NRAS exon 2 (c12/13),NRAS exon 3 (c61),NRAS exon 4 (c117/146),BRAF exon 15 (c600),Wild-type,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,Wild-type
2,4,KRAS exon 2 (c12/13),KRAS exon 3 (c61),KRAS exon 4 (c117/146),NRAS exon 2 (c12/13),NRAS exon 3 (c61),NRAS exon 4 (c117/146),BRAF exon 15 (c600),Mutant,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0,Mutant
3,5,KRAS exon 2 (c12/13),KRAS exon 3 (c61),KRAS exon 4 (c117/146),NRAS exon 2 (c12/13),NRAS exon 3 (c61),NRAS exon 4 (c117/146),BRAF exon 15 (c600),Mutant,Wild-type,Wild-type,Wild-type,Wild-type,Wild-type,Wild-type,1,6,0,Mutant
4,6,KRAS exon 2 (c12/13),KRAS exon 3 (c61),KRAS exon 4 (c117/146),NRAS exon 2 (c12/13),NRAS exon 3 (c61),NRAS exon 4 (c117/146),BRAF exon 15 (c600),Wild-type,Wild-type,Wild-type,Wild-type,Wild-type,Wild-type,Wild-type,0,7,0,Wild-type
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,458,KRAS exon 2 (c12/13),KRAS exon 3 (c61),KRAS exon 4 (c117/146),NRAS exon 2 (c12/13),NRAS exon 3 (c61),NRAS exon 4 (c117/146),BRAF exon 15 (c600),Wild-type,Wild-type,Wild-type,Wild-type,Wild-type,Wild-type,Wild-type,0,7,0,Wild-type
366,459,KRAS exon 2 (c12/13),KRAS exon 3 (c61),KRAS exon 4 (c117/146),NRAS exon 2 (c12/13),NRAS exon 3 (c61),NRAS exon 4 (c117/146),BRAF exon 15 (c600),Wild-type,Wild-type,Wild-type,Wild-type,Wild-type,Wild-type,Wild-type,0,7,0,Wild-type
367,460,KRAS exon 2 (c12/13),KRAS exon 3 (c61),KRAS exon 4 (c117/146),NRAS exon 2 (c12/13),NRAS exon 3 (c61),NRAS exon 4 (c117/146),BRAF exon 15 (c600),Failure,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,Unknown
368,461,KRAS exon 2 (c12/13),KRAS exon 3 (c61),KRAS exon 4 (c117/146),NRAS exon 2 (c12/13),NRAS exon 3 (c61),NRAS exon 4 (c117/146),BRAF exon 15 (c600),Mutant,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0,Mutant
369,462,KRAS exon 2 (c12/13),KRAS exon 3 (c61),KRAS exon 4 (c117/146),NRAS exon 2 (c12/13),NRAS exon 3 (c61),NRAS exon 4 (c117/146),BRAF exon 15 (c600),Mutant,Wild-type,Wild-type,Wild-type,Wild-type,Wild-type,Failure,1,5,1,Mutant

In [22]:
bio_before = pd.read_csv('../csv_file/BIOMARK_PDS2019.csv')
bio_before

,SUBJID,BMMTNM1,BMMTR1,BMMTNM2,BMMTR2,BMMTNM3,BMMTR3,BMMTNM4,BMMTR4,BMMTNM5,BMMTR5,BMMTNM6,BMMTR6,BMMTNM7,BMMTR7
0,1,KRAS exon 2 (c12/13),Failure,KRAS exon 3 (c61),NaN,KRAS exon 4 (c117/146),NaN,NRAS exon 2 (c12/13),NaN,NRAS exon 3 (c61),NaN,NRAS exon 4 (c117/146),NaN,BRAF exon 15 (c600),NaN
1,2,KRAS exon 2 (c12/13),Wild-type,KRAS exon 3 (c61),NaN,KRAS exon 4 (c117/146),NaN,NRAS exon 2 (c12/13),NaN,NRAS exon 3 (c61),NaN,NRAS exon 4 (c117/146),NaN,BRAF exon 15 (c600),NaN
2,4,KRAS exon 2 (c12/13),Mutant,KRAS exon 3 (c61),NaN,KRAS exon 4 (c117/146),NaN,NRAS exon 2 (c12/13),NaN,NRAS exon 3 (c61),NaN,NRAS exon 4 (c117/146),NaN,BRAF exon 15 (c600),NaN
3,5,KRAS exon 2 (c12/13),Mutant,KRAS exon 3 (c61),Wild-type,KRAS exon 4 (c117/146),Wild-type,NRAS exon 2 (c12/13),Wild-type,NRAS exon 3 (c61),Wild-type,NRAS exon 4 (c117/146),Wild-type,BRAF exon 15 (c600),Wild-type
4,6,KRAS exon 2 (c12/13),Wild-type,KRAS exon 3 (c61),Wild-type,KRAS exon 4 (c117/146),Wild-type,NRAS exon 2 (c12/13),Wild-type,NRAS exon 3 (c61),Wild-type,NRAS exon 4 (c117/146),Wild-type,BRAF exon 15 (c600),Wild-type
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,458,KRAS exon 2 (c12/13),Wild-type,KRAS exon 3 (c61),Wild-type,KRAS exon 4 (c117/146),Wild-type,NRAS exon 2 (c12/13),Wild-type,NRAS exon 3 (c61),Wild-type,NRAS exon 4 (c117/146),Wild-type,BRAF exon 15 (c600),Wild-type
390,459,KRAS exon 2 (c12/13),Wild-type,KRAS exon 3 (c61),Wild-type,KRAS exon 4 (c117/146),Wild-type,NRAS exon 2 (c12/13),Wild-type,NRAS exon 3 (c61),Wild-type,NRAS exon 4 (c117/146),Wild-type,BRAF exon 15 (c600),Wild-type
391,460,KRAS exon 2 (c12/13),Failure,KRAS exon 3 (c61),NaN,KRAS exon 4 (c117/146),NaN,NRAS exon 2 (c12/13),NaN,NRAS exon 3 (c61),NaN,NRAS exon 4 (c117/146),NaN,BRAF exon 15 (c600),NaN
392,461,KRAS exon 2 (c12/13),Mutant,KRAS exon 3 (c61),NaN,KRAS exon 4 (c117/146),NaN,NRAS exon 2 (c12/13),NaN,NRAS exon 3 (c61),NaN,NRAS exon 4 (c117/146),NaN,BRAF exon 15 (c600),NaN
393,462,KRAS exon 2 (c12/13),Mutant,KRAS exon 3 (c61),Wild-type,KRAS exon 4 (c117/146),Wild-type,NRAS exon 2 (c12/13),Wild-type,NRAS exon 3 (c61),Wild-type,NRAS exon 4 (c117/146),Wild-type,BRAF exon 15 (c600),Failure

In [7]:
adls = pd.read_csv("../csv_file/ADLS_PDS2019.csv")
adls

,SUBJID,VISITDY,VISIT,LSCAT,LSNEW,LSSLD,LSLD,LSSITE,LSNEWANY,LSREADER,LSTYPE
0,1,85.0,Week 12,Target lesion,N,210.0,32.0,Liver,N,Radiologist 1,Central
1,1,85.0,Week 12,Target lesion,N,300.0,51.0,Liver,Y,Radiologist 2,Central
2,1,85.0,Week 12,Target lesion,N,210.0,53.0,Liver,N,Radiologist 1,Central
3,1,85.0,Week 12,Target lesion,N,300.0,37.0,Liver,Y,Radiologist 2,Central
4,1,85.0,Week 12,Target lesion,N,210.0,32.0,Liver,N,Radiologist 1,Central
...,...,...,...,...,...,...,...,...,...,...,...
9930,461,-1.0,Screening,Non-target lesion,N,245.0,NaN,Pulmonary,N,Radiologist 2,Central
9931,461,-1.0,Screening,Non-target lesion,N,219.0,NaN,Lymph Nodes,N,Radiologist 1,Central
9932,461,-1.0,Screening,Non-target lesion,N,245.0,NaN,Lymph Nodes,N,Radiologist 2,Central
9933,461,-1.0,Screening,Non-target lesion,N,219.0,NaN,Gastrointestinal,N,Radiologist 1,Central
9934,461,-1.0,Screening,Non-target lesion,N,245.0,NaN,Lymph Nodes,N,Radiologist 2,Central

In [8]:
adrsp = pd.read_csv("../csv_file/ADRSP_PDS2019.csv")
adrsp

,SUBJID,RSRESP,VISITDY,VISIT,RSCONFYN,RSTRESP,RSNTRESP,RSREADER
0,1,Unknown,NaN,Screening,NaN,Unknown,Unknown,Radiologist 1
1,1,Unknown,NaN,Screening,NaN,Unknown,Unknown,Radiologist 2
2,1,Unknown,NaN,Screening,NaN,Unknown,Unknown,Oncologist
3,1,Unable to evaluate,50.0,Week 8,NaN,Stable disease,Stable disease,Radiologist 1
4,1,Unable to evaluate,50.0,Week 8,NaN,Stable disease,Stable disease,Radiologist 2
...,...,...,...,...,...,...,...,...
2297,461,Progressive disease,54.0,Week 8,NaN,Progressive disease,Progressive disease,Radiologist 1
2298,461,Progressive disease,54.0,Week 8,NaN,Progressive disease,Progressive disease,Radiologist 2
2299,461,Progressive disease,54.0,Week 8,NaN,Progressive disease,Progressive disease,Oncologist
2300,462,Unknown,NaN,Screening,NaN,Unknown,Unknown,Oncologist
2301,462,Progressive disease,62.0,Week 8,NaN,Not applicable,Progressive disease,Oncologist

In [10]:
adls = adls.drop(columns=["LSTYPE"])
adls

,SUBJID,VISITDY,VISIT,LSCAT,LSNEW,LSSLD,LSLD,LSSITE,LSNEWANY,LSREADER
0,1,85.0,Week 12,Target lesion,N,210.0,32.0,Liver,N,Radiologist 1
1,1,85.0,Week 12,Target lesion,N,300.0,51.0,Liver,Y,Radiologist 2
2,1,85.0,Week 12,Target lesion,N,210.0,53.0,Liver,N,Radiologist 1
3,1,85.0,Week 12,Target lesion,N,300.0,37.0,Liver,Y,Radiologist 2
4,1,85.0,Week 12,Target lesion,N,210.0,32.0,Liver,N,Radiologist 1
...,...,...,...,...,...,...,...,...,...,...
9930,461,-1.0,Screening,Non-target lesion,N,245.0,NaN,Pulmonary,N,Radiologist 2
9931,461,-1.0,Screening,Non-target lesion,N,219.0,NaN,Lymph Nodes,N,Radiologist 1
9932,461,-1.0,Screening,Non-target lesion,N,245.0,NaN,Lymph Nodes,N,Radiologist 2
9933,461,-1.0,Screening,Non-target lesion,N,219.0,NaN,Gastrointestinal,N,Radiologist 1
9934,461,-1.0,Screening,Non-target lesion,N,245.0,NaN,Lymph Nodes,N,Radiologist 2

In [24]:
adrsp = adrsp[(adrsp['RSRESP'] != 'Unknown') & (adrsp['VISIT'] != 'Screening')].copy()

In [22]:
adrsp

,SUBJID,RSRESP,VISITDY,VISIT,RSCONFYN,RSTRESP,RSNTRESP,RSREADER
3,1,Unable to evaluate,50.0,Week 8,NaN,Stable disease,Stable disease,Radiologist 1
4,1,Unable to evaluate,50.0,Week 8,NaN,Stable disease,Stable disease,Radiologist 2
5,1,Unable to evaluate,50.0,Week 8,NaN,Stable disease,Stable disease,Oncologist
6,1,Progressive disease,85.0,Week 12,NaN,Stable disease,Progressive disease,Radiologist 1
7,1,Progressive disease,85.0,Week 12,NaN,Stable disease,Progressive disease,Radiologist 2
...,...,...,...,...,...,...,...,...
2293,460,Progressive disease,47.0,Week 8,NaN,Stable disease,Progressive disease,Oncologist
2297,461,Progressive disease,54.0,Week 8,NaN,Progressive disease,Progressive disease,Radiologist 1
2298,461,Progressive disease,54.0,Week 8,NaN,Progressive disease,Progressive disease,Radiologist 2
2299,461,Progressive disease,54.0,Week 8,NaN,Progressive disease,Progressive disease,Oncologist
2301,462,Progressive disease,62.0,Week 8,NaN,Not applicable,Progressive disease,Oncologist

In [21]:
adrsp['RSRESP'].value_counts()

RSRESP
Progressive disease    833
Stable disease         276
Partial response       145
Unable to evaluate     100
Name: count, dtype: int64

In [39]:
adsl = pd.read_csv("csv_file/ADSL_PDS2019.csv")
adrsp = pd.read_csv("csv_file/ADRSP_PDS2019.csv")

adrsp = adrsp[(adrsp['RSRESP'] != 'Unknown') & (adrsp['VISIT'] != 'Screening')].copy()

# Radiologist 1 으로 기준
reader_rank = {'Radiologist 1': 1,'Radiologist 2':2,'Oncologist':3}
adrsp['_rank'] = adrsp['RSREADER'].map(reader_rank)

adrsp = (adrsp.sort_values(by=['SUBJID','VISITDY','_rank'])
         .groupby(['SUBJID', 'VISITDY'], as_index=False)
          .first())
resp_rank = {
    "Complete response":   1, # 없지만 그냥 넣어놈(국제 표준이라고해서)
    "Partial response":    2,
    "Stable disease":      3,
    "Progressive disease": 4,
    "Unable to evaluate":  5,
}
adrsp['_resp'] = adrsp['RSRESP'].map(resp_rank)

# BOR로 가장 좋았던 판정으로 판정
adrsp = (adrsp.sort_values(['SUBJID', '_resp'])
            .groupby('SUBJID', as_index=False)
            .first()[['SUBJID', 'RSRESP']]
            .rename(columns={'RSRESP': 'BOR'}))

adrsp['RESPONDER'] = adrsp['BOR'].isin(['Complete response', 'Partial response']).astype(int)

final = adsl.merge(adrsp, on='SUBJID', how='left')

final['BOR'] = final['BOR'].fillna('unknown')

# 43명이 평가를 못 받아서 0으로
final['RESPONDER'] = final['RESPONDER'].fillna(0).astype(int)

In [40]:
final

,SUBJID,TRT,ATRT,SXANY,DTHDYX,DTHX,PFSDYCR,PFSCR,DIAGMONS,AGE,SEX,B_WEIGHT,RACE,B_ECOG,HISSUBTY,DIAGTYPE,BOR,RESPONDER
0,1,panit. plus best supportive care,panit. plus best supportive care,Y,218,1,84,1,55.0,68,Male,48.0,White or Caucasian,Symptoms but ambulatory,No sub-type,Colon,Progressive disease,0
1,2,Best supportive care,Best supportive care,Y,231,1,57,1,25.0,48,Male,88.0,White or Caucasian,Symptoms but ambulatory,Mucinous,Colon,Progressive disease,0
2,4,Best supportive care,Best supportive care,Y,581,1,581,1,19.0,70,Female,57.0,White or Caucasian,Fully active,No sub-type,Colon,Unable to evaluate,0
3,5,Best supportive care,Best supportive care,Y,15,1,15,1,7.0,68,Female,64.4,White or Caucasian,In bed less than 50% of the time,No sub-type,Colon,Unable to evaluate,0
4,6,panit. plus best supportive care,panit. plus best supportive care,Y,286,1,112,1,30.0,56,Male,83.5,White or Caucasian,Fully active,No sub-type,Rectal,Stable disease,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,458,Best supportive care,Best supportive care,Y,501,1,54,1,36.0,71,Female,63.0,White or Caucasian,Symptoms but ambulatory,No sub-type,Rectal,Progressive disease,0
366,459,Best supportive care,Best supportive care,Y,485,0,55,1,NaN,32,Female,62.5,White or Caucasian,Fully active,No sub-type,Rectal,Progressive disease,0
367,460,Best supportive care,Best supportive care,Y,64,1,46,1,39.0,53,Female,75.0,White or Caucasian,Fully active,No sub-type,Colon,Progressive disease,0
368,461,panit. plus best supportive care,panit. plus best supportive care,N,175,1,53,1,9.0,76,Male,72.0,White or Caucasian,Fully active,No sub-type,Rectal,Progressive disease,0
369,462,panit. plus best supportive care,panit. plus best supportive care,Y,504,1,61,1,45.0,66,Female,79.0,White or Caucasian,Fully active,No sub-type,Rectal,Progressive disease,0

In [42]:
final.to_csv("csv_file/adsl_responder.csv", index=False)

In [35]:
adsl

,TRT,ATRT,SXANY,DTHDYX,DTHX,PFSDYCR,PFSCR,DIAGMONS,AGE,SEX,B_WEIGHT,RACE,B_ECOG,HISSUBTY,DIAGTYPE
SUBJID,,,,,,,,,,,,,,,
1,panit. plus best supportive care,panit. plus best supportive care,Y,218,1,84,1,55.0,68,Male,48.0,White or Caucasian,Symptoms but ambulatory,No sub-type,Colon
2,Best supportive care,Best supportive care,Y,231,1,57,1,25.0,48,Male,88.0,White or Caucasian,Symptoms but ambulatory,Mucinous,Colon
4,Best supportive care,Best supportive care,Y,581,1,581,1,19.0,70,Female,57.0,White or Caucasian,Fully active,No sub-type,Colon
5,Best supportive care,Best supportive care,Y,15,1,15,1,7.0,68,Female,64.4,White or Caucasian,In bed less than 50% of the time,No sub-type,Colon
6,panit. plus best supportive care,panit. plus best supportive care,Y,286,1,112,1,30.0,56,Male,83.5,White or Caucasian,Fully active,No sub-type,Rectal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
458,Best supportive care,Best supportive care,Y,501,1,54,1,36.0,71,Female,63.0,White or Caucasian,Symptoms but ambulatory,No sub-type,Rectal
459,Best supportive care,Best supportive care,Y,485,0,55,1,NaN,32,Female,62.5,White or Caucasian,Fully active,No sub-type,Rectal
460,Best supportive care,Best supportive care,Y,64,1,46,1,39.0,53,Female,75.0,White or Caucasian,Fully active,No sub-type,Colon
461,panit. plus best supportive care,panit. plus best supportive care,N,175,1,53,1,9.0,76,Male,72.0,White or Caucasian,Fully active,No sub-type,Rectal
462,panit. plus best supportive care,panit. plus best supportive care,Y,504,1,61,1,45.0,66,Female,79.0,White or Caucasian,Fully active,No sub-type,Rectal

In [34]:
adrsp

     SUBJID                  BOR  RESPONDER
0         1  Progressive disease          0
1         2  Progressive disease          0
2         4   Unable to evaluate          0
3         5   Unable to evaluate          0
4         6       Stable disease          0
..      ...                  ...        ...
322     458  Progressive disease          0
323     459  Progressive disease          0
324     460  Progressive disease          0
325     461  Progressive disease          0
326     462  Progressive disease          0

[327 rows x 3 columns]

In [28]:
# Radiologist 1 으로 기준
adrsp1 = adrsp[(adrsp['RSRESP'] != 'Unknown') & (adrsp['VISIT'] != 'Screening')].copy()
reader_rank = {'Radiologist 1': 2,'Radiologist 2':1,'Oncologist':1}
adrsp1['_rank'] = adrsp['RSREADER'].map(reader_rank)

adrsp1 = (adrsp.sort_values(by=['SUBJID','VISITDY','_rank'])
         .groupby(['SUBJID', 'VISITDY'], as_index=False)
          .first())

adrsp1['_rank'].value_counts()

_rank
1    368
3    250
2      6
Name: count, dtype: int64